version: '3'

services:
  db4devs-app:
    build: .
    container_name: db4devs-app
    environment:
      - REDIS_URL=redis:6379
    depends_on:
      - redis
    ports:
      - "6000:6000"
    networks:
      - db4devs-network

  redis:
    image: "redis:6.2.5"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - db4devs-network

networks:
  db4devs-network:
    driver: bridge